### ISSUE TITLE
[Feature Request]: Mint a PyPI release

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/pymatgen-io-validation#48]
### Problem

This is an issue tracker for a forthcoming PyPI release. I'm opening this so I can keep track on when this is done 😄 

### Proposed Solution

🚀

**Comment by esoteric-ephemera** [comment]
Absolutely will do. We're in alpha testing but will hopefully have a pypi release soon!

**Comment by matthewkuner** [comment]
@Andrew-S-Rosen a pypi release has been minted: https://pypi.org/project/pymatgen-io-validation/
