### ISSUE TITLE
Perhaps check for electronic convergence in *every* ionic step?

### ISSUE THREAD

**Issue by matthewkuner** [materialsproject/pymatgen-io-validation#73]
https://github.com/materialsproject/pymatgen-io-validation/blob/d256508e8af6896f08064ffaea8f076097223b46/pymatgen/io/validation/check_common_errors.py#L82

**Comment by esoteric-ephemera** [comment]
I think this makes more sense. Implemented this, and hopefully a fix for possible bug in linear response calculations in [e7cd875](https://github.com/materialsproject/pymatgen-io-validation/commit/e7cd8756fbd946661dad515ee0cbf14c7e2c942c)
